import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Sidebar from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  variable: "--font-geist-sans",
  src: "./fonts/GeistVF.woff",
  weight: "100 900",
});

const geistMono = localFont({
  variable: "--font-geist-mono",
  src: "./fonts/GeistMonoVF.woff",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Hotel Directory",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <StoreProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {" "}
          <div className="h-screen flex bg-gray-100">
            <Sidebar />
            <main className="flex-1 overflow-y-auto p-8">
              <div className="max-w-11xl mx-auto  sm:px-6 lg:px-8">
                {children}
              </div>
            </main>
          </div>
          <Toaster />
        </body>
      </StoreProvider>
    </html>
  );
};

export default RootLayout;
